type Chapter @collection(name: "chapters") {
  id: ID!
  title: String!
  entryPoint: Boolean!
  author: Author! @relation
  body: String!
  choices: [Choice!]
}

type Author @collection(name: "authors") {
  name: String!
  identity: String!
  image: String!
  email: String!
}

type Choice @embedded {
  id: ID!
  title: String!
  continuation: Chapter! @relation
}

type Query {
  allChapters: [Chapter!]! @index(name: "all_chapters")
  allAuthors: [Author!]! @index(name: "all_authors")
  author(identity: String): Author
  entrypoints(entryPoint: Boolean): [Chapter!]
  chapter(id: ID!): Chapter
}
