type Chapter @collection(name: "chapters") {
  # id: ID!
  title: String!
  entryPoint: Boolean!
  author: Author! @relation
  body: String!
  choices: [Choice!]
}

type Author @collection(name: "authors") {
  name: String!
  identity: String!
  image: String!
  email: String!
}

type Choice @embedded {
  title: String!
  continuation: Chapter! @relation
}

type Query {
  # allChapters: [Chapter!]! @index(name: "all_chapters")
  # allAuthors: [Author!]! @index(name: "all_authors")
  author(identity: String): Author
  entrypoints(entryPoint: Boolean): [Chapter!]
  # chapter(id: ID!): Chapter
}

type Mutation {
  # prettier-ignore
  addChoiceToChapter(chapterId: ID!, choiceTitle: String!, choiceContinuation: ID!): Chapter! @resolver(name: "add_choice_to_chapter")
}
